warts {
  # Can't call .get() on Option/Try/Either
  OptionPartial = Error
  TryPartial = Error
  EitherProjectionPartial = Error
  # Can't escape Scala type system
  IsInstanceOf = Error
  AsInstanceOf = Error
  # Can't use null keyword, avoiding NullPointerException
  Null = Error
  # Can't use the return keyword
  Return = Error
  # ??? must not be accidentally push in production code
  TripleQuestionMark = Error
  # Stops scala compiler to infer Any, avoiding mixing types
  # val l = List(1, true, "three"), :type(l) = List[Any] won't compile
  Any = Error
  # Can't append object to a string, use string interpolation instead
  StringPlusAny = Error
  # Can't use throw keyword, use right return type instead
  Throw = Error
  # Can't ignore values returned by functions
  NonUnitStatements = Error
}
